openapi: 3.0.3
info:
  title: Library API Docs - PT Eigen Tri Mathema Backend Test
  description: -
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:4001/api/v1
    description: Development server
tags:
  - name: books
    description: Operations about books and borrow/return
  - name: members
    description: Operations about members
paths:
  /books/:
    get:
      tags:
        - books
      summary: Get available books
      description: Returns a list of books that are available to borrow
      operationId: getBooks
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Books'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Books'
  /books/borrow:
    post:
      tags:
        - books
      summary: Borrow a book
      description: Borrow a book
      operationId: borrowBook
      requestBody:
        description: Borrow a book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
          application/xml:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
        required: true
  /books/return:
    post:
      tags:
        - books
      summary: Return a book
      description: Return a book
      operationId: returnBook
      requestBody:
        description: Return a book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
          application/xml:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BorrowReturnBook'
        required: true
  /members/:
    get:
      tags:
        - members
      summary: Get all members
      description: Returns a list of members
      operationId: getMembers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Members'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Members'
components:
  schemas:
    Books:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        code:
          type: string
          example: 'JK-45'
        title:
          type: string
          example: 'Harry Potter'
        author:
          type: string
          example: 'J.K. Rowling'
        stock:
          type: integer
          format: int32
          example: 1
      xml:
        name: books
    BorrowReturnBook:
      required:
        - memberCode
        - bookCode
      type: object
      properties:
        memberCode:
          type: string
          example: "M001"
        bookCode:
          type: string
          example: "JK-45"
      xml:
        name: borrowreturnBook
    Members:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        code:
          type: string
          example: 'M001'
        name:
          type: string
          name: 'Angga'
        penalty:
          type: boolean
          example: false
        penaltyUpTo:
          type: string
          example: '2023-09-22'
        borrowedBooks:
          type: integer
          format: int64
          example: 2
      xml:
        name: members
    ApiResponse:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        data:
          type: array
          items:
            type: object
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    BorrowReturnBook:
      description: Borrow and Return Book object that needs to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BorrowReturnBook'
        application/xml:
          schema:
            $ref: '#/components/schemas/BorrowReturnBook'